Traceback (most recent call last):
  File "6_lipids_final.py", line 113, in <module>
    get_ipython().run_line_magic('load_ext', 'autoreload')
NameError: name 'get_ipython' is not defined
Traceback (most recent call last):
  File "6_lipids_final.py", line 394, in <module>
    sns.lineplot(h_molecules[h_molecules["human"] == "HA"].loc[:, h_molecules.columns.str.contains("FA")])
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/relational.py", line 692, in lineplot
    p = _LinePlotter(
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/relational.py", line 367, in __init__
    super().__init__(data=data, variables=variables)
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/_core.py", line 605, in __init__
    self.assign_variables(data, variables)
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/_core.py", line 668, in assign_variables
    plot_data, variables = self._assign_variables_longform(
  File "/gss/home/m.zybin/.local/lib/python3.8/site-packages/seaborn/_core.py", line 927, in _assign_variables_longform
    plot_data = pd.DataFrame(plot_data)
  File "/opt/python/lib/python3.8/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/python/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/opt/python/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/opt/python/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
Traceback (most recent call last):
  File "6_lipids_final.py", line 766, in <module>
    importances_df = pd.DataFrame(np.vstack([np.array(common_molecules), result.importances_mean]).T, columns=["feature name", "importance"])
  File "<__array_function__ internals>", line 5, in vstack
  File "/opt/python/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 318 and the array at index 1 has size 15900
Traceback (most recent call last):
  File "6_lipids_final.py", line 877, in <module>
    print(pd.DataFrame(common_molecules[rf.feature_importances_.argsort()][:-6:-1]).to_latex())
TypeError: only integer scalar arrays can be converted to a scalar index
